<?php namespace DreamFactory\Enterprise\Console\Tests\Http\Controllers;

use DreamFactory\Library\Utility\Curl;
use Illuminate\Http\Response;

class FastTrackControllerTest extends \TestCase
{
    static $_userId;

    public function testAutoRegister()
    {
        $_response = $this->post('http://console.dfe.3wipes.com/fast-track',
            [
                'email'      => 'mistertestler@gmail.com',
                'password'   => 'password',
                'first-name' => 'Mister',
                'last-name'  => 'Testler',
                'nickname'   => 'Mister',
            ]);

        $this->assertNotEmpty($_response->getStatus() != Response::HTTP_BAD_REQUEST);
    }

    public static function tearDownAfterClass()
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub

        try {
            \Artisan::call('dfe:deprovision', ['instance-id' => 'mistertestler']);
            Curl::delete('/ops/v1/user/' . $_response['user']['id']);
        } catch (\Exception $_ex) {
        }
    }

}
