#!/bin/sh

php artisan dfe:move-instance dfe-db-east-3 todd2 >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 todd3 >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 todd45g >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 dsp123 >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 nictest >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 gta >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 jstables >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 drewpearce >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 jess >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 dave-test >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 dave2 >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 flavaflave >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 cja >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 demo >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 tardis >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-jeffrey >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-thisistheend >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-iostest >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-cthulu >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-jjstables >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-lee >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-testing >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-tryagain >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-dfdf >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-nandemo >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-qwertyzxw >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-naninani >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-dfdfdf >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-dfhershmo >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-sdghsd >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-werthweth >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-sdfhwdfhg >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-test123456 >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-toddhosted >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-wiki >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-aha >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-todd444 >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-dfetest >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-qwe >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-asd-1 >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-benbusse >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-dfhershexample >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-dferic >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-anotherone >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-snapshot >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-zzz >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-zzz2 >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-hello123 >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-drewnew >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-fgfgf >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-todd911 >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-dave1 >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-halpme >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-infracaninophile >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 froope >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 herg >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 dearg >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 ghur >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 froopq >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 jkil >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 hger >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 wert >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 hgre >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 fghe >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 tronk >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 goip >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-ft-lirt >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-ft-jkol >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-ft-plws >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-ft-kqih >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-ft-qorp >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-woohoo >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-firefly >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-another >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-another-one >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-qwerty22 >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-qwerty23 >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-friday >>/data/logs/console/move-instance-one.log 2>&1
php artisan dfe:move-instance dfe-db-east-3 df-gha >>/data/logs/console/move-instance-one.log 2>&1
