CREATE TABLE `instance_t` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `vendor_id` int(11) NOT NULL,
  `vendor_image_id` int(11) NOT NULL DEFAULT '0',
  `vendor_credentials_id` int(11) NOT NULL,
  `instance_id_text` varchar(64) CHARACTER SET latin1 DEFAULT NULL,
  `flavor_nbr` int(11) NOT NULL DEFAULT '0',
  `image_name_text` varchar(128) CHARACTER SET latin1 NOT NULL,
  `region_text` varchar(32) CHARACTER SET latin1 DEFAULT NULL,
  `availability_zone_text` varchar(32) CHARACTER SET latin1 DEFAULT NULL,
  `security_group_text` varchar(1024) CHARACTER SET latin1 DEFAULT NULL,
  `ssh_key_text` varchar(64) CHARACTER SET latin1 DEFAULT NULL,
  `root_device_type_nbr` int(11) NOT NULL DEFAULT '0',
  `public_host_text` varchar(256) CHARACTER SET latin1 DEFAULT NULL,
  `public_ip_text` varchar(20) CHARACTER SET latin1 DEFAULT NULL,
  `private_host_text` varchar(256) CHARACTER SET latin1 DEFAULT NULL,
  `private_ip_text` varchar(20) CHARACTER SET latin1 DEFAULT NULL,
  `create_date` datetime NOT NULL,
  `lmod_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_instance_vendor_id` (`vendor_id`),
  KEY `fk_instance_vendor_image_id` (`vendor_image_id`),
  KEY `fk_instance_vendor_credentials_id` (`vendor_credentials_id`),
  CONSTRAINT `fk_instance_vendor_credentials_id` FOREIGN KEY (`vendor_credentials_id`) REFERENCES `vendor_credentials_t` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_instance_vendor_id` FOREIGN KEY (`vendor_id`) REFERENCES `vendor_t` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_instance_vendor_image_id` FOREIGN KEY (`vendor_image_id`) REFERENCES `vendor_image_t` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;