<?php
//******************************************************************************
//* Instance names that are forbidden, feel free to add/subtract
//******************************************************************************
return [
    /** reserved */
    'dreamfactory',
    'dream',
    'factory',
    'developer',
    'wiki',
    'enterprise',
    'cloud',
    'www',
    'fabric',
    'api',
    'db',
    'database',
    'dsp',
    'dfe',
    'dfac',
    'df',
    'dfab',
    'dfdsp',
    'email',
    'rave',
    'console',
    'dashboard',
    'launchpad',
    'test',
    'performance_schema',
    'information_schema',
    'mysql',
    'postgresql',
    'oracle',
    'dfe_local',
    /** icky */
    'feces',
    'fecal',
    'defecate',
    'urinate',
    'inseminate',
    'cum',
    'jizz',
    'semen',
    /** The holy seven... */
    'shit',
    'piss',
    'fuck',
    'cunt',
    'cocksucker',
    'motherfucker',
    'tits',
];
